apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:  
      containers:
      - name: meu-deployment
        image: ghcr.io/luizarodrigues98/scheduling-app:latest
      imagePullSecrets:
      - name: regcred1
